import {database,ensureSchema} from "../_db";

function internalError(error:unknown){if(error instanceof Error)return {name:error.name,message:error.message,stack:error.stack};return {message:String(error)}}
function errorJson(step:string,error:unknown,status=500){console.error("[REGISTRATION ERROR]",{step,status,...internalError(error)});const safe=status<500?(error instanceof Error?error.message:String(error)):"Não foi possível concluir a inscrição";return Response.json({success:false,step,error:safe},{status})}
async function ensureRecentColumns(){const db=database();const pi=(await db.prepare("PRAGMA table_info(players)").all()).results as {name:string}[],pc=new Set(pi.map(x=>x.name));if(!pc.has("discord_type"))await db.prepare("ALTER TABLE players ADD COLUMN discord_type TEXT NOT NULL DEFAULT 'numeric_id'").run();if(!pc.has("discord_value"))await db.prepare("ALTER TABLE players ADD COLUMN discord_value TEXT").run();const ti=(await db.prepare("PRAGMA table_info(teams)").all()).results as {name:string}[],tc=new Set(ti.map(x=>x.name));if(!tc.has("deleted_at"))await db.prepare("ALTER TABLE teams ADD COLUMN deleted_at INTEGER").run();const ci=(await db.prepare("PRAGMA table_info(team_coaches)").all()).results as {name:string}[],cc=new Set(ci.map(x=>x.name));if(!cc.has("instagram"))await db.prepare("ALTER TABLE team_coaches ADD COLUMN instagram TEXT").run()}
async function settings(){const db=database();await db.prepare("INSERT OR IGNORE INTO competition_settings(id,min_starters,max_starters,max_reserves,coach_required) VALUES('current',4,4,2,0)").run();return await db.prepare("SELECT * FROM competition_settings WHERE id='current'").first() as any}

export async function GET(r:Request){try{await ensureSchema();await ensureRecentColumns();const u=new URL(r.url),slug=u.searchParams.get("slug"),all=u.searchParams.get("all")==="1";let q="SELECT * FROM teams",v:string[]=[],w:string[]=["deleted_at IS NULL"];if(slug){w.push("slug=?");v.push(slug)}if(!all){w.push("status=?");v.push("APROVADA")}if(w.length)q+=" WHERE "+w.join(" AND ");q+=" ORDER BY created_at DESC";const rows=(await database().prepare(q).bind(...v).all()).results as any[];const data=await Promise.all(rows.map(async t=>({...t,players:(await database().prepare("SELECT * FROM players WHERE team_id=? ORDER BY roster_type,created_at").bind(t.id).all()).results,coach:await database().prepare("SELECT * FROM team_coaches WHERE team_id=? LIMIT 1").bind(t.id).first()})));return Response.json({success:true,teams:data})}catch(error){return errorJson("load_teams",error)}}

export async function POST(r:Request){let step="starting_submission";try{
  console.info("[REGISTRATION] Starting submission");await ensureSchema();await ensureRecentColumns();const limits=await settings();if(limits.registration_start&&Date.now()<new Date(limits.registration_start).getTime())return errorJson("registrations",new Error("As inscrições ainda não começaram"),403);if(!limits.registrations_open)return errorJson("registrations",new Error("As inscrições estão encerradas"),403);if(limits.registration_end&&Date.now()>=new Date(limits.registration_end).getTime())return errorJson("registrations",new Error("O prazo de inscrições foi encerrado"),403);
  step="parse_body";const b=await r.json() as any,submissionKey=String(b.submissionKey||"").trim();
  if(!submissionKey)return errorJson("request",new Error("Identificador do envio ausente"),400);
  const existing=await database().prepare("SELECT registration_id,team_id,status FROM registrations WHERE submission_key=? LIMIT 1").bind(submissionKey).first() as any;
  if(existing){console.info("[REGISTRATION] Existing successful submission returned",{teamId:existing.team_id});return Response.json({success:true,registrationId:existing.registration_id,teamId:existing.team_id,status:existing.status,message:"Inscrição realizada com sucesso"},{status:200})}
  if(!b.name||!b.tag||!b.country||!["BR","NORTE","SUR"].includes(b.region)||!b.responsible?.name||!b.responsible?.email)return errorJson("team",new Error("Dados obrigatórios da equipe ou responsável ausentes"),400);
  if(!Array.isArray(b.players))return errorJson("players",new Error("Lista de jogadoras inválida"),400);
  const starters=b.players.filter((p:any)=>p.rosterType==="TITULAR"),reserves=b.players.filter((p:any)=>p.rosterType==="RESERVA");
  if(starters.length<limits.min_starters||starters.length>limits.max_starters)return errorJson("players",new Error(`A equipe precisa de ${limits.min_starters} a ${limits.max_starters} titulares`),400);
  if(reserves.length>limits.max_reserves)return errorJson("players",new Error(`Máximo de ${limits.max_reserves} reservas`),400);
  for(let i=0;i<b.players.length;i++){const p=b.players[i],value=String(p.discordValue||p.discordId||"");if(!p.nickname||!p.freefireId||!value)return errorJson("players",new Error(`PLAYER ${i+1}: revise Nick, Free Fire ID e Discord`),400);if(p.discordType==="numeric_id"&&!/^\d+$/.test(value))return errorJson("players",new Error(`PLAYER ${i+1}: Discord ID deve conter somente números`),400)}
  if(limits.coach_required&&!b.coach?.skip&&(!b.coach?.nickname||!b.coach?.discordValue))return errorJson("coach",new Error("Preencha os dados obrigatórios do coach"),400);
  const id=crypto.randomUUID(),registrationRowId=crypto.randomUUID(),responsibleId=crypto.randomUUID(),now=Date.now(),slug=String(b.name).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")+"-"+id.slice(0,6),reg=`DL-S1-${Math.floor(1000+Math.random()*9000)}`,db=database(),statements=[];
  step="team";console.info("[REGISTRATION] Creating team");statements.push(db.prepare("INSERT INTO teams(id,registration_id,name,slug,tag,country,region,group_name,logo_url,instagram,discord,status,responsible_name,responsible_nick,responsible_email,responsible_whatsapp,responsible_discord,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,reg,b.name,slug,b.tag,b.country,b.region,null,b.logoUrl||null,b.instagram||null,b.discord||null,"EM ANÁLISE",b.responsible.name,b.responsible.nick||null,b.responsible.email,b.responsible.whatsapp||null,b.responsible.discord||null,now,now));
  step="players";console.info("[REGISTRATION] Creating players",{count:b.players.length});for(const p of b.players){const dv=String(p.discordValue||p.discordId||"");statements.push(db.prepare("INSERT INTO players(id,team_id,nickname,full_name,freefire_id,discord_id,discord_type,discord_value,country,role,roster_type,photo_url,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,p.nickname,p.fullName||null,p.freefireId,dv,p.discordType||"numeric_id",dv,p.country||b.country,p.role,p.rosterType||"TITULAR",p.photoUrl||null,now))}
  step="coach";console.info("[REGISTRATION] Creating coach",{included:Boolean(b.coach&&!b.coach.skip)});if(b.coach&&!b.coach.skip)statements.push(db.prepare("INSERT INTO team_coaches(id,team_id,full_name,nickname,country,photo_url,discord_type,discord_value,whatsapp,instagram,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,b.coach.fullName||"",b.coach.nickname||"",b.coach.country||b.country,b.coach.photoUrl||null,b.coach.discordType||"username",b.coach.discordValue||"",b.coach.whatsapp||null,b.coach.instagram||null,now));
  step="responsible";console.info("[REGISTRATION] Creating responsible");statements.push(db.prepare("INSERT INTO team_responsibles(id,team_id,full_name,nickname,email,whatsapp,discord,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(responsibleId,id,b.responsible.name,b.responsible.nick||null,b.responsible.email,b.responsible.whatsapp||null,b.responsible.discord||null,now));
  step="registration";console.info("[REGISTRATION] Creating registration");statements.push(db.prepare("INSERT INTO registrations(id,registration_id,team_id,submission_key,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(registrationRowId,reg,id,submissionKey,"EM ANÁLISE",now,now));
  step="database_transaction";await db.batch(statements);console.info("[REGISTRATION] Success",{registrationId:reg,teamId:id});return Response.json({success:true,registrationId:reg,teamId:id,slug,status:"EM ANÁLISE",message:"Inscrição realizada com sucesso"},{status:201});
}catch(error){return errorJson(step,error)}}
